### PR TITLE
Configurable timestamp

### LINKED ISSUE #522: Make timestamp in output configurable (so that results are more reproducible)
**What happened**:

grype generates different output content for the same image, which breaks the reproducibility.

Motivation comes from the https://github.com/in-toto/attestation/issues/58 to put output result digest in the vuln spec. _cc: @developer-guy_

Not sure whether this is intentional or time/map object related.

**What you expected to happen**:

All the output results for the exactly same `IMAGE@sha256:digest` should generate the same digest. 

**How to reproduce it (as minimally and precisely as possible)**:

```bash
$ docker image pull golang:1.17
$ grype golang:1.17 --output cyclonedx --file result1
$ docker image rmi golang:1.17
$ grype golang:1.17 --output cyclonedx --file result2
$ sha256sum result1
5ce609c4b26876f6394d57182346bbf46bc863753010b990b862d49caa9874ee result1
$ sha256sum result2
d1929364ecb727d14615d1b813f3c9b499ada7ef4979ff1c933c73444fdff84d result2
```

```bash
$ grype golang:1.17 --output json --file json1
$ grype golang:1.17 --output json --file json2
$ sha256sum json1
c9883e5a2c64631448145beaf20af51a1d085f3d47bba3db6555d28839a82072  json1
$ sha256sum json2
c0e2090127d7ba33f3b6f09732a26789f5c65f9c7068063507813793b35d44a3  json2
```

**Anything else we need to know?**:

I tried the same commands with the [trivy](https://github.com/aquasecurity/trivy). And both SARIF & JSON output formats produced same digest:

```bash
$ trivy image --format template --template "@./sarif.tpl" -o report1.sarif golang:1.17
$ trivy image --format template --template "@./sarif.tpl" -o report2.sarif golang:1.17
$ sha256sum 2fcf23e25debe08f3b5490f077bd926d85afc67c94df28f173bd0aa766e4ce24 report1.sarif
$ sha256sum 2fcf23e25debe08f3b5490f077bd926d85afc67c94df28f173bd0aa766e4ce24 report2.sarif
```

Maybe we can get help from the trivy team so cc'ing @knqyf263.

`trivy`: `0.21.2`

**Environment**:
- Output of `grype version`: `0.26.1`
- OS (e.g: `cat /etc/os-release` or similar): `macOS 11`

### PR DESCRIPTION
**Pull request by gabetrau**
Allows for configuring whether or not to include a timestamp in the final output via config option or env variable. Default is true. Resolves #522

### CODE REVIEW

File: grype/presenter/models/document.go [hunk 1]
```diff
@@ -20,10 +21,18 @@ type Document struct {
...
 
 // NewDocument creates and populates a new Document struct, representing the populated JSON document.
-func NewDocument(id clio.Identification, packages []pkg.Package, context pkg.Context, matches match.Matches, ignoredMatches []match.IgnoredMatch, metadataProvider vulnerability.MetadataProvider, appConfig any, dbInfo any, strategy SortStrategy) (Document, error) {
-	timestamp, timestampErr := time.Now().Local().MarshalText()
-	if timestampErr != nil {
-		return Document{}, timestampErr
+func NewDocument(id clio.Identification, packages []pkg.Package, context pkg.Context, matches match.Matches, ignoredMatches []match.IgnoredMatch, metadataProvider vulnerability.MetadataProvider, appConfig any, dbInfo any, strategy SortStrategy, outputTimestamp bool) (Document, error) {
+	var timestamp []byte
+
+	if !outputTimestamp || os.Getenv("GRYPE_TIMESTAMP") == "false" {
```
Comment (wagoodman) [inline grype/presenter/models/document.go]: All environment vars should be resolved up in the `cmd` package and not down in the library (it seems like this is already accounted for).
```suggestion
	if !outputTimestamp {
```
