### PR TITLE
Derive OS distribution from purl

### LINKED ISSUE #2630: Grype does not handle purl file input with packages from different distributions
**What happened**:

Running `grype purl:input.txt` with package urls from different distributions causes Grype to not output any vulnerabilities.

**What you expected to happen**:

Grype correctly identifies vulnerabilities of the passed packages.

**How to reproduce it (as minimally and precisely as possible)**:

First, run Grype separately to verify that the passed purls are valid and vulnerable.

```bash
grype 'pkg:rpm/ol/bzip2-libs@1.0.8-8.el9?arch=x86_64&distro=ol-9.5&upstream=bzip2-1.0.8-8.el9.src.rpm'
grype 'pkg:deb/ubuntu/coreutils@9.4-3ubuntu6?arch=amd64&distro=ubuntu-24.04&upstream=coreutils%409.4-3ubuntu6'
```

Now create a file `input.txt` with the purls

```
pkg:deb/ubuntu/coreutils@9.4-3ubuntu6?arch=amd64&distro=ubuntu-24.04&upstream=coreutils%409.4-3ubuntu6
pkg:rpm/ol/bzip2-libs@1.0.8-8.el9?arch=x86_64&distro=ol-9.5&upstream=bzip2-1.0.8-8.el9.src.rpm
```

Run grype on the file

```
grype purl:input.txt
```

Notice that Grype does not find any vulnerabilities. Grype outputs the following warning:

```
WARN Unable to determine the OS distribution. This may result in missing vulnerabilities. You may specify a distro using: --distro <distro>:<version>
```

However the distribution information is already present in the package URL: `distro=ubuntu-24.04` and `distro=ol-9.5`. Grype disregards it and expects all packages to come from a single distro.

**Environment**:
- Output of `grype version`:

```
Application:         grype
Version:             0.91.2
BuildDate:           2025-04-25T17:20:02Z
GitCommit:           7e6ba817350bdb922f35e4437aa01869cf0a8be0
GitDescription:      v0.91.2
Platform:            linux/amd64
GoVersion:           go1.24.2
Compiler:            gc
Syft Version:        v1.23.1
Supported DB Schema: 6
```

- OS (e.g: `cat /etc/os-release` or similar): Arch Linux

### PR DESCRIPTION
**Pull request by chovanecadam**
closes #2630

### CODE REVIEW

File: grype/pkg/purl_provider.go [hunk 1]
```diff
@@ -203,6 +205,13 @@ func purlToPackage(rawLine string) (*Package, *pkg.Package, string, string, erro
 	}
 
 	syftPkg.SetID()
+
+	distribution, err := distro.NewFromRelease(*createLinuxRelease(distroName, distroVersion))
+	if err != nil {
+		log.Trace("Unable to create Disto from a release: %s", err)
```
Comment (kzantow) [inline grype/pkg/purl_provider.go:211]: nit: spelling: `Disto` -> `Distro`

Comment (chovanecadam) [reply grype/pkg/purl_provider.go]: I fixed the spelling issue and added an ignore statement for the lint issue. I look at the function and I am not sure how to make it smaller without sacrificing readability.
